run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - revive

issues:
  exclude-use-default: false
  # Exclude generated files
  exclude:
    - "_test\\.go"$
    - "(pb|grpc)\\.pb\\.go$"
